apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubec-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubec
  template:
    metadata:
      labels:
        app: kubec
    spec:
      containers:
        - name: kubec
          image: kaneshiya/kubec
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Served by $(hostname)" >> /usr/local/apache2/htdocs/index.html && \
              httpd-foreground